In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('listings.csv.gz')

In [4]:
df.head()

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2818,https://www.airbnb.com/rooms/2818,20210208155251,2021-02-11,Quiet Garden View Room & Super Fast WiFi,Quiet Garden View Room & Super Fast WiFi<br />...,"Indische Buurt (""Indies Neighborhood"") is a ne...",https://a0.muscache.com/pictures/10272854/8dcc...,3159,https://www.airbnb.com/users/show/3159,...,10.0,9.0,10.0,NaN,t,1,0,1,0,1.92
1,20168,https://www.airbnb.com/rooms/20168,20210208155251,2021-02-11,Studio with private bathroom in the centre 1,17th century Dutch townhouse in the heart of t...,Located just in between famous central canals....,https://a0.muscache.com/pictures/69979628/fd6a...,59484,https://www.airbnb.com/users/show/59484,...,10.0,10.0,9.0,NaN,t,2,0,2,0,2.54
2,25428,https://www.airbnb.com/rooms/25428,20210208155251,2021-02-10,"Lovely, spacious 1 bed apt in Center(with lift)",Lovely apt in Centre ( lift & fireplace) near ...,NaN,https://a0.muscache.com/pictures/138431/7079a9...,56142,https://www.airbnb.com/users/show/56142,...,10.0,10.0,10.0,NaN,f,1,1,0,0,0.13
3,27886,https://www.airbnb.com/rooms/27886,20210208155251,2021-02-11,"Romantic, stylish B&B houseboat in canal district",Stylish and romantic houseboat on fantastic hi...,"Central, quiet, safe, clean and beautiful.",https://a0.muscache.com/pictures/02c2da9d-660e...,97647,https://www.airbnb.com/users/show/97647,...,10.0,10.0,10.0,NaN,t,1,0,1,0,1.98
4,28871,https://www.airbnb.com/rooms/28871,20210208155251,2021-02-10,Comfortable double room,<b>The space</b><br />In a monumental house ri...,"Flower market , Leidseplein , Rembrantsplein",https://a0.muscache.com/pictures/160889/362340...,124245,https://www.airbnb.com/users/show/124245,...,10.0,10.0,10.0,NaN,f,2,0,2,0,2.63

In [5]:
df.shape

(18291, 74)

In [6]:
df_numeric = df.select_dtypes(include=['float64'])

In [7]:
df_string = df.select_dtypes(include=['object'])

In [8]:
df_int = df.select_dtypes(include=['int'])

In [9]:
print(df_numeric.shape)
print(df_string.shape)
print(df_int.shape)

(18291, 24)
(18291, 33)
(18291, 17)

In [10]:
df_numeric.describe()

,host_listings_count,host_total_listings_count,neighbourhood_group_cleansed,latitude,longitude,bathrooms,bedrooms,beds,minimum_minimum_nights,maximum_minimum_nights,...,calendar_updated,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,reviews_per_month
count,18228.000000,18228.000000,0.0,18291.000000,18291.000000,0.0,17294.000000,18186.000000,18288.000000,18288.000000,...,0.0,15659.000000,15649.000000,15649.000000,15641.000000,15648.000000,15643.000000,15643.000000,0.0,15902.000000
mean,3.244459,3.244459,NaN,52.365478,4.889504,NaN,1.534405,1.765259,3.683454,3.861494,...,NaN,95.107287,9.690907,9.457857,9.750911,9.794926,9.513456,9.202071,NaN,0.591448
std,56.575963,56.575963,NaN,0.016559,0.035833,NaN,0.959211,1.444775,16.287296,16.389708,...,NaN,7.035600,0.728646,0.914985,0.659262,0.636390,0.705519,0.832326,NaN,1.065085
min,0.000000,0.000000,NaN,52.289270,4.755940,NaN,1.000000,0.000000,1.000000,1.000000,...,NaN,20.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,NaN,0.010000
25%,1.000000,1.000000,NaN,52.355100,4.863920,NaN,1.000000,1.000000,2.000000,2.000000,...,NaN,93.000000,10.000000,9.000000,10.000000,10.000000,9.000000,9.000000,NaN,0.130000
50%,1.000000,1.000000,NaN,52.364790,4.887010,NaN,1.000000,1.000000,2.000000,2.000000,...,NaN,97.000000,10.000000,10.000000,10.000000,10.000000,10.000000,9.000000,NaN,0.280000
75%,1.000000,1.000000,NaN,52.375370,4.909230,NaN,2.000000,2.000000,3.000000,3.000000,...,NaN,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,NaN,0.580000
max,7235.000000,7235.000000,NaN,52.425120,5.027690,NaN,50.000000,35.000000,1001.000000,1001.000000,...,NaN,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,NaN,35.530000

In [11]:
df_numeric.isnull().sum()

host_listings_count                63
host_total_listings_count          63
neighbourhood_group_cleansed    18291
latitude                            0
longitude                           0
bathrooms                       18291
bedrooms                          997
beds                              105
minimum_minimum_nights              3
maximum_minimum_nights              3
minimum_maximum_nights              3
maximum_maximum_nights              3
minimum_nights_avg_ntm              3
maximum_nights_avg_ntm              3
calendar_updated                18291
review_scores_rating             2632
review_scores_accuracy           2642
review_scores_cleanliness        2642
review_scores_checkin            2650
review_scores_communication      2643
review_scores_location           2648
review_scores_value              2648
license                         18291
reviews_per_month                2389
dtype: int64

In [12]:
drop_list = ['neighbourhood_group_cleansed', 'bathrooms', 'calendar_updated', 'license']

In [15]:
drop_list.extend(['latitude', 'longitude'])

In [17]:
df_numeric.drop(columns = drop_list, axis = 1).head()

,host_listings_count,host_total_listings_count,bedrooms,beds,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
0,1.0,1.0,1.0,2.0,3.0,3.0,1125.0,1125.0,3.0,1125.0,98.0,10.0,10.0,10.0,10.0,9.0,10.0,1.92
1,2.0,2.0,1.0,1.0,1.0,4.0,60.0,1125.0,3.8,413.8,89.0,10.0,10.0,10.0,10.0,10.0,9.0,2.54
2,2.0,2.0,1.0,1.0,14.0,14.0,180.0,180.0,14.0,180.0,100.0,10.0,10.0,10.0,10.0,10.0,10.0,0.13
3,1.0,1.0,1.0,1.0,2.0,2.0,1125.0,1125.0,2.0,1125.0,99.0,10.0,10.0,10.0,10.0,10.0,10.0,1.98
4,2.0,2.0,1.0,1.0,2.0,2.0,1825.0,1825.0,2.0,1825.0,97.0,10.0,10.0,10.0,10.0,10.0,10.0,2.63

In [19]:
df_numeric.drop(columns = drop_list, axis = 1).describe()

,host_listings_count,host_total_listings_count,bedrooms,beds,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
count,18228.000000,18228.000000,17294.000000,18186.000000,18288.000000,18288.000000,18288.000000,1.828800e+04,18288.000000,1.828800e+04,15659.000000,15649.000000,15649.000000,15641.000000,15648.000000,15643.000000,15643.000000,15902.000000
mean,3.244459,3.244459,1.534405,1.765259,3.683454,3.861494,688.285652,2.355498e+05,3.768269,2.350138e+05,95.107287,9.690907,9.457857,9.750911,9.794926,9.513456,9.202071,0.591448
std,56.575963,56.575963,0.959211,1.444775,16.287296,16.389708,536.932318,2.245690e+07,16.347635,2.240609e+07,7.035600,0.728646,0.914985,0.659262,0.636390,0.705519,0.832326,1.065085
min,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000e+00,1.000000,1.000000e+00,20.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,0.010000
25%,1.000000,1.000000,1.000000,1.000000,2.000000,2.000000,28.000000,2.800000e+01,2.000000,2.800000e+01,93.000000,10.000000,9.000000,10.000000,10.000000,9.000000,9.000000,0.130000
50%,1.000000,1.000000,1.000000,1.000000,2.000000,2.000000,1125.000000,1.125000e+03,2.000000,1.125000e+03,97.000000,10.000000,10.000000,10.000000,10.000000,10.000000,9.000000,0.280000
75%,1.000000,1.000000,2.000000,2.000000,3.000000,3.000000,1125.000000,1.125000e+03,3.000000,1.125000e+03,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,0.580000
max,7235.000000,7235.000000,50.000000,35.000000,1001.000000,1001.000000,11250.000000,2.147484e+09,1001.000000,2.142625e+09,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,35.530000

In [18]:
df_int.describe()

,id,scrape_id,host_id,accommodates,minimum_nights,maximum_nights,availability_30,availability_60,availability_90,availability_365,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms
count,1.829100e+04,1.829100e+04,1.829100e+04,18291.000000,18291.000000,18291.000000,18291.000000,18291.000000,18291.000000,18291.000000,18291.000000,18291.000000,18291.000000,18291.000000,18291.000000,18291.000000,18291.000000
mean,2.064229e+07,2.021021e+13,6.705998e+07,2.837570,3.727407,611.559565,5.950467,12.473621,19.262315,61.923132,24.125198,1.520147,0.023892,2.647477,2.111366,0.476628,0.009404
std,1.285836e+07,0.000000e+00,8.666877e+07,1.282434,16.331468,545.438112,11.195839,22.753660,34.282051,115.602325,54.560889,6.552857,0.260227,8.724302,8.545412,1.457147,0.153398
min,2.818000e+03,2.021021e+13,3.159000e+03,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,1.010732e+07,2.021021e+13,9.282300e+06,2.000000,2.000000,21.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000
50%,1.911168e+07,2.021021e+13,2.810956e+07,2.000000,2.000000,1125.000000,0.000000,0.000000,0.000000,0.000000,8.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000
75%,3.039472e+07,2.021021e+13,8.650474e+07,4.000000,3.000000,1125.000000,0.000000,9.000000,18.000000,78.000000,22.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000
max,4.807786e+07,2.021021e+13,3.871652e+08,16.000000,1001.000000,11250.000000,30.000000,60.000000,90.000000,365.000000,859.000000,380.000000,10.000000,85.000000,84.000000,21.000000,5.000000

In [21]:
df_int.isnull().sum()

id                                              0
scrape_id                                       0
host_id                                         0
accommodates                                    0
minimum_nights                                  0
maximum_nights                                  0
availability_30                                 0
availability_60                                 0
availability_90                                 0
availability_365                                0
number_of_reviews                               0
number_of_reviews_ltm                           0
number_of_reviews_l30d                          0
calculated_host_listings_count                  0
calculated_host_listings_count_entire_homes     0
calculated_host_listings_count_private_rooms    0
calculated_host_listings_count_shared_rooms     0
dtype: int64

In [25]:
df_string.head()

,listing_url,last_scraped,name,description,neighborhood_overview,picture_url,host_url,host_name,host_since,host_location,...,property_type,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
0,https://www.airbnb.com/rooms/2818,2021-02-11,Quiet Garden View Room & Super Fast WiFi,Quiet Garden View Room & Super Fast WiFi<br />...,"Indische Buurt (""Indies Neighborhood"") is a ne...",https://a0.muscache.com/pictures/10272854/8dcc...,https://www.airbnb.com/users/show/3159,Daniel,2008-09-24,"Amsterdam, Noord-Holland, The Netherlands",...,Private room in apartment,Private room,1.5 shared baths,"[""Hangers"", ""Coffee maker"", ""Paid parking on p...",$59.00,t,2021-02-11,2009-03-30,2020-02-14,t
1,https://www.airbnb.com/rooms/20168,2021-02-11,Studio with private bathroom in the centre 1,17th century Dutch townhouse in the heart of t...,Located just in between famous central canals....,https://a0.muscache.com/pictures/69979628/fd6a...,https://www.airbnb.com/users/show/59484,Alexander,2009-12-02,"Amsterdam, Noord-Holland, The Netherlands",...,Private room in townhouse,Private room,1 private bath,"[""Essentials"", ""Bed linens"", ""Hot water"", ""Han...",$129.00,t,2021-02-11,2010-03-02,2020-04-09,t
2,https://www.airbnb.com/rooms/25428,2021-02-10,"Lovely, spacious 1 bed apt in Center(with lift)",Lovely apt in Centre ( lift & fireplace) near ...,NaN,https://a0.muscache.com/pictures/138431/7079a9...,https://www.airbnb.com/users/show/56142,Joan,2009-11-20,"New York, New York, United States",...,Entire apartment,Entire home/apt,1 bath,"[""Hangers"", ""Elevator"", ""Cooking basics"", ""Dis...",$125.00,t,2021-02-10,2018-01-21,2020-02-09,f
3,https://www.airbnb.com/rooms/27886,2021-02-11,"Romantic, stylish B&B houseboat in canal district",Stylish and romantic houseboat on fantastic hi...,"Central, quiet, safe, clean and beautiful.",https://a0.muscache.com/pictures/02c2da9d-660e...,https://www.airbnb.com/users/show/97647,Flip,2010-03-23,"Amsterdam, Noord-Holland, The Netherlands",...,Private room in houseboat,Private room,1.5 baths,"[""Patio or balcony"", ""Hangers"", ""Dishes and si...",$125.00,t,2021-02-11,2012-01-09,2020-07-25,t
4,https://www.airbnb.com/rooms/28871,2021-02-10,Comfortable double room,<b>The space</b><br />In a monumental house ri...,"Flower market , Leidseplein , Rembrantsplein",https://a0.muscache.com/pictures/160889/362340...,https://www.airbnb.com/users/show/124245,Edwin,2010-05-13,"Amsterdam, Noord-Holland, The Netherlands",...,Private room in apartment,Private room,1 shared bath,"[""Hot water"", ""Essentials"", ""Smoke alarm"", ""Ha...",$75.00,t,2021-02-10,2010-08-22,2020-09-20,f

In [22]:
df_string.columns

Index(['listing_url', 'last_scraped', 'name', 'description',
       'neighborhood_overview', 'picture_url', 'host_url', 'host_name',
       'host_since', 'host_location', 'host_about', 'host_response_time',
       'host_response_rate', 'host_acceptance_rate', 'host_is_superhost',
       'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood',
       'host_verifications', 'host_has_profile_pic', 'host_identity_verified',
       'neighbourhood', 'neighbourhood_cleansed', 'property_type', 'room_type',
       'bathrooms_text', 'amenities', 'price', 'has_availability',
       'calendar_last_scraped', 'first_review', 'last_review',
       'instant_bookable'],
      dtype='object')

In [42]:
drop_list_string = ['listing_url', 'last_scraped', 'name', 'picture_url', 'host_url', 'host_name', 'host_thumbnail_url', \
                    'host_picture_url']
potential_important_string = ['host_since', 'host_location', 'response_rate', 'host_acceptance_rate', 'host_is_superhost'\
                             'host_identity_vrified', 'some sort of location', 'neighbourhood', 'neighbourhood_cleansed'\
                             'property_type', 'room_type', 'bathrooms_text', 'instant_bookable']
maybe_string = ['description', 'host_about', 'neighborhood_overview', 'host_location', 'host_response_time', \
                'host_neighborhood', 'host_verifications', 'host_has_profile_pic', 'amenities', 'has_availability']
target = ['price']

In [24]:
df_string['host_about'][0]

'Upon arriving in Amsterdam, one can imagine asking oneself: Where is the fun nightlife? What are the local hot spots? \r\n\r\nHow can I experience the real life in this city? I  offer you the opportunity to act, eat and sleep like-a-local!  \r\n\r\nI provide the traveler with the opportunity to connect with the local life in Amsterdam.'

In [26]:
df_string['description'][0]

'Quiet Garden View Room & Super Fast WiFi<br /><br /><b>The space</b><br />I\'m renting a bedroom (room overlooking the garden) in my apartment in Amsterdam, <br /><br />The room is located to the east of the city centre in a quiet, typical Amsterdam neighbourhood the "Indische Buurt". Amsterdamâ€™s historic centre is less than 15 minutes away by bike or tram.<br /><br /><br />The features of the room are:<br /><br />- Twin beds (80 x 200 cm, down quilts and pillows) <br />- 2 pure cotton towels for each guest <br />- reading lamps<br />- bedside table<br />- wardrobe<br />- table with chairs<br />- tea and coffee making facilities<br />- mini bar<br />- alarm clock<br />- Hi-Fi system with cd player, connection for mp3 player / phone<br />- map of Amsterdam and public transport<br />- Wi-Fi Internet connection <br /><br />Extra services:<br /><br />- Bike rental'

In [29]:
df_string['neighborhood_overview'][0]

'Indische Buurt ("Indies Neighborhood") is a neighbourhood in the eastern portion of the city of Amsterdam, in the Dutch province of Noord-Holland. The name dates from the early 20th century and is derived from the fact that the neighbourhood\'s streets are named after islands and other geographical concepts in the former Dutch colony of the Dutch East Indies. The first street was named in 1902. In 2003, there were around 23,357 inhabitants. The neighbourhood is bounded on the west by the railroad Amsterdam - Hilversum (with the Muiderpoort Station), on the east side by Flevopark, on the north side by Zeeburgerdijk and on the south side by the Ringvaart Watergraafsmeer. Indische Buurt is the oldest part of the Zeeburg district and is very ethnically diverse, and a high percentage of the population is of immigrant origin (for Zeeburg this is already high at 55%, but higher in the Indische Buurt) and there are an estimated 100 languages spoken.'

In [28]:
df_string['last_scraped'].value_counts()

2021-02-09    7486
2021-02-10    6051
2021-02-11    3301
2021-02-08    1453
Name: last_scraped, dtype: int64

In [31]:
df_string['host_location'].value_counts()

Amsterdam, North Holland, Netherlands                    10046
Amsterdam, North Holland, The Netherlands                 3515
NL                                                        1549
Amsterdam, Noord-Holland, The Netherlands                 1153
Netherlands                                                520
                                                         ...
Patras, Greece                                               1
Mannheim, Baden-Wurttemberg, Germany                         1
Coux-et-Bigaroque-Mouzens, Nouvelle-Aquitaine, France        1
Madison, Wisconsin, United States                            1
Caen, Normandy, France                                       1
Name: host_location, Length: 534, dtype: int64

In [34]:
df_string['host_response_time'].value_counts()

within an hour        1800
within a day           900
within a few hours     838
a few days or more     399
Name: host_response_time, dtype: int64

In [35]:
df_string['host_response_rate'].value_counts()

100%    2794
0%       286
50%      106
90%       81
70%       69
60%       63
67%       55
80%       55
75%       53
33%       43
89%       41
88%       30
93%       23
86%       22
96%       17
83%       16
82%       15
63%       15
41%       13
65%       12
40%       12
77%       11
95%       11
38%        7
91%        7
72%        6
92%        6
57%        6
97%        5
25%        5
78%        5
85%        4
17%        4
30%        4
29%        3
20%        3
64%        3
10%        3
99%        3
94%        3
43%        2
71%        2
53%        2
31%        2
73%        2
44%        2
56%        2
14%        1
58%        1
11%        1
Name: host_response_rate, dtype: int64

In [36]:
df_string['host_acceptance_rate'].value_counts()

100%    3638
0%       812
50%      407
99%      253
67%      217
        ...
4%         1
41%        1
23%        1
15%        1
7%         1
Name: host_acceptance_rate, Length: 89, dtype: int64

In [37]:
df_string['host_is_superhost'].value_counts()

f    15849
t     2379
Name: host_is_superhost, dtype: int64

In [38]:
df_string['host_neighbourhood'].value_counts()

Oud-West             2482
De Pijp              1061
Grachtengordel        728
Jordaan               685
Oosterparkbuurt       675
                     ...
Sant Antoni             1
La Latina               1
Beguinage-Dixmude       1
Recoleta                1
Le Plateau              1
Name: host_neighbourhood, Length: 76, dtype: int64

In [41]:
df_string['host_verifications']

0        ['email', 'phone', 'reviews', 'jumio', 'offlin...
1        ['email', 'phone', 'reviews', 'jumio', 'offlin...
2                            ['email', 'phone', 'reviews']
3        ['email', 'phone', 'reviews', 'jumio', 'offlin...
4        ['email', 'phone', 'reviews', 'jumio', 'offlin...
                               ...
18286                ['email', 'phone', 'identity_manual']
18287    ['email', 'phone', 'facebook', 'reviews', 'jum...
18288                          ['email', 'phone', 'jumio']
18289    ['phone', 'facebook', 'jumio', 'offline_govern...
18290                                   ['email', 'phone']
Name: host_verifications, Length: 18291, dtype: object

In [43]:
df_string['host_has_profile_pic'].value_counts()
# maybe category due to lack of variance

t    18199
f       29
Name: host_has_profile_pic, dtype: int64

In [44]:
df_string['host_identity_verified'].value_counts()

t    11918
f     6310
Name: host_identity_verified, dtype: int64

In [46]:
df_string['neighbourhood'].value_counts()

Amsterdam, Noord-Holland, Netherlands             9534
Amsterdam, North Holland, Netherlands             1490
Amsterdam, NH, Netherlands                         700
Amsterdam, Netherlands                             110
Amsterdam-Zuidoost, Noord-Holland, Netherlands      57
                                                  ...
Halfweg, NH, Netherlands                             1
Amsterdam, NB, Netherlands                           1
Amsterdam, TL, Netherlands                           1
AmsterdÃ£o, North Holland, Netherlands                1
Amsterdam, GA, Netherlands                           1
Name: neighbourhood, Length: 67, dtype: int64

In [47]:
df_string['neighbourhood_cleansed'].value_counts()

De Baarsjes - Oud-West                    3044
De Pijp - Rivierenbuurt                   2269
Centrum-West                              2000
Centrum-Oost                              1560
Westerpark                                1395
Zuid                                      1309
Oud-Oost                                  1181
Bos en Lommer                             1047
Oostelijk Havengebied - Indische Buurt     875
Oud-Noord                                  586
Watergraafsmeer                            530
IJburg - Zeeburgereiland                   423
Slotervaart                                411
Noord-West                                 369
Noord-Oost                                 255
Buitenveldert - Zuidas                     252
Geuzenveld - Slotermeer                    214
De Aker - Nieuw Sloten                     126
Osdorp                                     125
Gaasperdam - Driemond                      121
Bijlmer-Centrum                            103
Bijlmer-Oost                                96
Name: neighbourhood_cleansed, dtype: int64

In [51]:
df_string['property_type'].value_counts()

Entire apartment                     11393
Private room in apartment             2218
Entire house                          1198
Entire townhouse                       472
Private room in bed and breakfast      344
                                     ...
Earth house                              1
Entire chalet                            1
Entire home/apt                          1
Bus                                      1
Tipi                                     1
Name: property_type, Length: 65, dtype: int64

In [52]:
df_string['room_type'].value_counts()

Entire home/apt    14283
Private room        3831
Hotel room           127
Shared room           50
Name: room_type, dtype: int64

In [53]:
df_string['bathrooms_text'].value_counts()

1 bath               10677
1.5 baths             3473
1 shared bath         1210
1 private bath        1043
2 baths                802
1.5 shared baths       466
2.5 baths              239
3 baths                 96
3.5 baths               43
Half-bath               39
0 baths                 38
Shared half-bath        32
2 shared baths          29
0 shared baths          15
4 baths                 13
Private half-bath       11
3 shared baths          10
3.5 shared baths         8
2.5 shared baths         6
4 shared baths           5
4.5 baths                4
8 baths                  3
5 baths                  2
6 baths                  2
12 baths                 1
13 baths                 1
5.5 baths                1
Name: bathrooms_text, dtype: int64

In [54]:
df_string['amenities'].value_counts()

["Long term stays allowed"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       45
["Essentials", "Smoke alarm", "Washer", "Heating", "TV", "Cable TV", "Wifi", "Kitchen", "Long term stays allowed", "Dryer"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       21
["Essentials", "Smoke alarm", "Kitchen", "Hangers", "Washer", "Heating", "Iron", "Dedicated workspace", "Shampoo", "TV", "Cable TV", "Wifi", "Hair dryer", "Long term stays allowed", "Dryer"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    21
["Essentials", "Washer", "Heating", "TV", "Cable TV", "Wifi", "Kitchen", "Long term stays allowed"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               18
["Essentials", "Smoke alarm", "Kitchen", "Hangers", "Washer", "Heating", "Iron", "Carbon monoxide alarm", "Dedicated workspace", "Shampoo", "TV", "Cable TV", "Wifi", "Hair dryer", "Long term stays allowed", "Dryer"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           13
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ..
["Hangers", "Cooking basics", "Dishes and silverware", "Oven", "Coffee maker", "Long term stays allowed", "Private entrance", "Dishwasher", "Carbon monoxide alarm", "Dedicated workspace", "Single level home", "Kitchen", "Hot water", "Heating", "Garden or backyard", "TV", "Cable TV", "Hair dryer", "Essentials", "Smoke alarm", "Stove", "Washer", "Refrigerator", "Iron", "Shampoo", "Wifi", "Dryer"]                                                                                                                                                                                                                                                                                                                      1
["Essentials", "Smoke alarm", "Kitchen", "Hangers", "Heating", "Iron", "Dedicated workspace", "Shampoo", "TV", "Cable TV", "Wifi", "Hair dryer", "Long term stays allowed", "Fire extinguisher", "First aid kit"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  1
["Essentials", "Smoke alarm", "Free parking on premises", "Washer", "Heating", "Host greets you", "TV", "Shampoo", "Cable TV", "Wifi", "Kitchen", "Fire extinguisher", "First aid kit"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1
["Changing table", "Hangers", "Cooking basics", "Dishes and silverware", "Oven", "Room-darkening shades", "Coffee maker", "Bathtub", "Paid parking on premises", "First aid kit", "Bed linens", "Outlet covers", "Private entrance", "Crib", "Dishwasher", "Carbon monoxide alarm", "Dedicated workspace", "Single level home", "Kitchen", "Hot water", "Paid parking off premises", "Heating", "Garden or backyard", "TV", "Baby bath", "Hair dryer", "Microwave", "Essentials", "Smoke alarm", "Stove", "Washer", "Hot tub", "Children\u2019s books and toys", "Refrigerator", "Iron", "Children\u2019s dinnerware", "High chair", "Shampoo", "Wifi", "Dryer"]                                                                   1
["Patio or balcony", "Changing table", "Babysitter recommendations", "Hangers", "Elevator", "Cooking basics", "Dishes and silverware", "Luggage dropoff allowed", "Oven", "Room-darkening shades", "Bathtub", "Long term stays allowed", "First aid kit", "Bed linens", "Building staff", "Dishwasher", "Carbon monoxide alarm", "Dedicated workspace", "Single level home", "Kitchen", "Extra pillows and blankets", "Heating", "TV", "Cable TV", "Free parking on premises", "Hair dryer", "Microwave", "Essentials", "Smoke alarm", "Stove", "Washer", "Children\u2019s books and toys", "Refrigerator", "Iron", "Children\u2019s dinnerware", "EV charger", "High chair", "Shampoo", "Wifi", "Fire extinguisher", "Dryer"]     1
Name: amenities, Length: 16744, dtype: int64

In [55]:
df_string['has_availability'].value_counts()
# maybe due to lack of variance

t    17889
f      402
Name: has_availability, dtype: int64

In [56]:
df_string['instant_bookable'].value_counts()

f    13914
t     4377
Name: instant_bookable, dtype: int64

In [ ]:
df_string['has_availability'].value_counts()